### ISSUE TITLE
Starting sequence

### ISSUE THREAD

**Issue by machinekoder** [aldadic/esp-smartmeter-reader#2]
First, thanks for publishing the code on GitHub.

I have a question regarding the start sequence of the telegram pushed from the meter: How did you find out the sequence?

I noticed that on my system I read something very similar in the data stream, but not exactly the same. I'm not using the ESP32, but I have a RS485 - USB converter connected to a RPi for reading an optical probe of the Wiener Netze smart meter. In my case there is an additional `0xFF` in between `0x7e` and `0xa0`, the distance between two `0xa0` is still 105 bytes. So I'm just wondering if that's a problem on my side or if I'm missing something in the code.

**Comment by aldadic** [comment]
I got all my information from [this thread](https://www.lteforum.at/mobilfunk/wiener-netze-smart-meter-auslesen.16222/). Unfortunately, I don't think that I can help you with your problem. The only thing I can say is that it seems like `0x7e 0xa0` is the starting sequence for all the people in said thread (and of course for me too), so my guess would be that there is a problem on your end.

**Comment by machinekoder** [comment]
@aldadic Thanks for the info. I found the problem yesterday. Apparently the optical probe head needs to be aligned with the port, so the cable is hanging downwards, else I get wrong readings. I wasn't expecting this, and it's nowhere noted in the datasheet of the probe or the meter.
