### ISSUE TITLE
How to deal with messages starting with DB not '7E A0'

### ISSUE THREAD

**Issue by chof747** [aldadic/esp-smartmeter-reader#4]
Hi Aldadic, 

I am currently writing an esphome component which should be able to read the smart meter interface of Wiener Netze - and in fact it does it - see here: https://github.com/chof747/smartmeter

However I am failing to implement the CRC check. I saw that you have implemented it in your code but it seems that the message format my meter is putting out is different from yours. I seem to have DLMS messages encrypted with AES_GCM and the telegrams start always with d8.

Do you have any idea where I can find more info about the CRC Check? - Or how that is composed? Thanks Christian

**Comment by aldadic** [comment]
Hi @chof747!

Sorry for the late reply! I unfortunately can't tell you where you can find more information about the CRC check. I got all my information from [this thread](https://www.lteforum.at/mobilfunk/wiener-netze-smart-meter-auslesen.16222/). Maybe someone there has an idea.

**Comment by horfic** [comment]
Hi, I'm also just writing a esphome dlms component, testing on a landis gyr e450 3 phase from stromnetz graz per phsyikal mbus and hdlc data link layer.

@chof747  you can have a look at my crc checking in there https://github.com/horfic/esphome-dlms
@aldadic would it be possible if you could test that code?

its not perfect yet and i have note yet mapped the sml data to the esphome variables, but that is not hard anymore, currently still trying to make it more dynamic to work with different providers.

example output
![image](https://github.com/aldadic/esp-smartmeter-reader/assets/994939/72ba6e7d-991c-45d7-b9fb-4fdd0c371698)

example esphome config snippet
![image](https://github.com/aldadic/esp-smartmeter-reader/assets/994939/7c8cd9ea-33cb-4c5c-813e-16b8cf39a475)

cheers,
Horfic

**Comment by aldadic** [comment]
Hi @chof747!
Sorry for the late reply! Unfortunately, I can't test your code because my ESP32 is positioned in such a way that it is really hassle to flash it.
