### ISSUE TITLE
Bit of trouble to get this working, GUEK or GAK key needed?

### ISSUE THREAD

**Issue by EpicLPer** [aldadic/esp-smartmeter-reader#5]
Heya,

Greetings from Austria!
I'm trying to get this project working on an ESP8266 (Wemos D1 Mini), got it compiled and hooked up and everything, however I'm not getting any results from my Landis+Gyr E450 meter.

Not sure if I've used the GUEK key I got from my provider in the right way tho.
Say, my example key would be `11223344556677889900AABBCCDDEEFF`, I've put it into the config like this: `const byte KEY[] = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x00, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff};`
Is this the correct way? The thing is I'm not even sure if my energy meter is sending out signals via IR. I've had an electrician come out and enable it apparently, but he didn't seem to know too much about what I wanted from him (seems like I'm the only one wanting to read data like this in my town :) ). I've also put my Flipper Zero in front of the interface and used an IR scope, but I didn't get any output from it.

Thanks already!

**Comment by aldadic** [comment]
Hi @EpicLPer!
Sorry for the late reply! This is the correct way to put the key into the config. However, I can't help you with your issue, since I am not that knowledgeable about smart meters 😅
